=== frankluebeck/OKUSON/server/fmTools/dtds/config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ==================================================================
     config.dtd - XML Document type definition for "Config.xml"
     Copyright 2003 Frank Lübeck and Max Neunhöffer
     ================================================================== -->

<!-- $Id$ -->

<!ELEMENT Config ANY>


<!-- The following make up the "Course" section: -->

<!ELEMENT AdministratorPassword (#PCDATA)>
<!ELEMENT CourseName (#PCDATA)>
<!ELEMENT Semester (#PCDATA)>
<!ELEMENT Lecturer (#PCDATA)>
<!ELEMENT Header (#PCDATA)>
<!ELEMENT Feedback (#PCDATA)>
<!ELEMENT Footer (#PCDATA)>
<!ELEMENT PossibleStudies (Option)*>
<!ELEMENT Port (#PCDATA)>
<!ELEMENT ExtraLaTeXHeader (#PCDATA)>
<!ELEMENT IdCheckRegExp (#PCDATA)>
<!ELEMENT GuestIdRegExp (#PCDATA)>
<!ELEMENT IndividualSheets (#PCDATA)>
<!ELEMENT RegistrationPossible (#PCDATA)>
<!ELEMENT ExamRegistrationPossible (#PCDATA)>
<!ELEMENT GroupChoicePossible (#PCDATA)>
<!ELEMENT GroupChangePossible (#PCDATA)>
<!ELEMENT ValidateRegistration (#PCDATA)>
<!ELEMENT ValidateRegistrationMail (#PCDATA)>
<!ELEMENT ValidEmailAddresses (#PCDATA)>
<!ELEMENT GradingFunction (#PCDATA)>
<!ELEMENT GradingActive (#PCDATA)>
<!ELEMENT ExamGradingFunction (#PCDATA)>
<!ELEMENT ExamGradingActive (#PCDATA)>
<!ELEMENT MaxStringInputLength (#PCDATA)>
<!ELEMENT KeptData (Option)*>
<!ELEMENT EMailHeaderFunction (#PCDATA)>
<!ELEMENT InteractiveMode (#PCDATA)>
<!ELEMENT RestrictToOwnGroup (#PCDATA)>
<!ELEMENT MCScoreCorrectDefault (#PCDATA)>
<!ELEMENT MCScoreWrongDefault (#PCDATA)>
<!ELEMENT MCScoreExerciseLowerLimitDefault (#PCDATA)>
<!ELEMENT StringCorrectAnswer (#PCDATA)>
<!ELEMENT StringWrongAnswer (#PCDATA)>
<!ELEMENT StringNoAnswer (#PCDATA)>
<!ELEMENT ProtectedFiles (#PCDATA)>

<!-- a container for extra data, use the 'key' attribute: -->
<!ELEMENT ConfigData (#PCDATA)>
<!ATTLIST ConfigData key CDATA #REQUIRED>

<!-- The following make up the "Installation" section: -->

<!ELEMENT AccessList (Range)*>
<!ELEMENT AdministrationAccessList (Range)*>
<!ELEMENT HashSalt (#PCDATA)>
<!ELEMENT DocumentRoot (#PCDATA)>
<!ELEMENT ExerciseDirectories (Dir)*>
<!ELEMENT SheetDirectories (Dir)*>
<!ELEMENT GeneralMessageFile (#PCDATA)>
<!ELEMENT RegistrationFile (#PCDATA)>
<!ELEMENT SubmissionFile (#PCDATA)>
<!ELEMENT HomeworkFile (#PCDATA)>
<!ELEMENT ExamRegistrationFile (#PCDATA)>
<!ELEMENT ExamFile (#PCDATA)>
<!ELEMENT GroupFile (#PCDATA)>
<!ELEMENT MessageFile (#PCDATA)>
<!ELEMENT GroupInfoFile (#PCDATA)>
<!ELEMENT PathToDTDs (#PCDATA)>
<!ELEMENT PDFTemplate (#PCDATA)>
<!ELEMENT PDFTemplateMoodle (#PCDATA)>
<!ELEMENT PDFTemplateNoTable (#PCDATA)>

<!-- The following make up the "Customization" section: -->

<!ELEMENT WidthOfSheetsHTML (#PCDATA)>
<!ELEMENT WidthOfExerciseTextsHTML (#PCDATA)>
<!ELEMENT WidthOfQuestionsHTML (#PCDATA)>
<!ELEMENT WidthOfSheetsPDF (#PCDATA)>
<!ELEMENT WidthOfExerciseTextsPDF (#PCDATA)>
<!ELEMENT WidthOfQuestionsPDF (#PCDATA)>
<!ELEMENT Resolutions (#PCDATA)>
<!ELEMENT LaTeXTemplate (#PCDATA)>
<!ELEMENT DateTimeFormat (#PCDATA)>

<!-- The following is used for lists of directory names: -->

<!ELEMENT Dir (#PCDATA)>
<!ELEMENT Option (#PCDATA)>
<!ELEMENT Range (#PCDATA)>

=== frankluebeck/OKUSON/Config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
 
<!-- This is the main configuration file for OKUSON. 
     Copyright (C) 2003 Frank Lübeck and Max Neunhöffer -->

<!DOCTYPE Config SYSTEM "config.dtd">

<Config>

<!-- Usually you will not have to add or remove any elements in this 
     file but just adjust the textual data between tags. Generally
     white space is removed at the beginning and end of each element.
     See the comments or the manual for explanations.

     This file contains three sections:

       Course section: 
               Every user will have to adjust the values in this section
               to customize things for the specific course.

       Installation section: 
               Only administrators who want to adjust the installation
               to special circumstances need to have a look at this
               section.
               
       Customization section: 
               In this section many aspects of OKUSON can be customized.
               WARNING: Usually one should leave this section alone.
                        He who feels inclined to change anything here
                        should know what he is doing!

-->

<!-- ====================================================================
                              Course section
     ==================================================================== -->

<!-- The following is the encrypted administrator password. Please use the
     "cryptpasswd" utility in the OKUSON home directory to encrypt some 
     password. 
     
     This password gives very powerful access to the OKUSON server, so
     choose it carefully: 
     It can be used as super-password in all web forms which ask for a 
     password (of any course participant, tutor or the administrator) 
     and is considered valid if the request is coming from a machine 
     as configured in AdministrationAccessList below.
     
     The default setting is secret, so you must change it! -->
<AdministratorPassword>
xvPTFipiaskI.
</AdministratorPassword>

<!-- The name of the course served by this directories' server: -->
<CourseName>
Lineare Algebra I
</CourseName>

<!-- The semester this course takes place in: -->
<Semester>
WS 2003/04
</Semester>

<!-- The lecturer: -->
<Lecturer>
Prof. Dr. Herbert Pahlings
</Lecturer>

<!-- A chunk of HTML code that should appear at the bottom of every page
     for feedback. Please enclose everything in a CDATA section as shown
     such that the XML parser reading this file sees only one big string. -->
<Feedback><![CDATA[
<br /><a href="mailto:frank.luebeck@math.rwth-aachen.de">
Frank Lübeck (Frank.Luebeck@Math.RWTH-Aachen.De)</a> oder
<br /><a href="mailto:neunhoef at mcs.st-and.ac.uk">
Max Neunhöffer (neunhoef at mcs.st-and.ac.uk)</a>
]]></Feedback>


<!-- The following is put as string (no element content allowed, use a
     CDATA section if necessary!) at the top of each page (directly behind
     the <body> tag of the xhtml page. -->
<Header></Header>


<!-- The following is put as string (no element content allowed, use a
     CDATA section if necessary!) at the bottom of each page (directly before
     the </body> tag of the xhtml page. -->
<Footer></Footer>


<!-- The following appears on the registration page under the entry
"Studiengang", which means the direction of studies. Note that there
is also a free form field which - when nonempty - overwrites the choice
given here. The available options appear each within an "Option" element.
The last plays a special role: It should be not a real option but
indicate that the free form field counts which is also available. -->
<PossibleStudies>
  <Option>Mathematik-Diplom</Option>
  <Option>Mathematik-Lehramt</Option>
  <Option>Physik-Diplom</Option>
  <Option>Physik-Lehramt</Option>
  <Option>Informatik-Diplom</Option>
  <Option>Schülerstudium</Option>
  <Option>Sonstiges</Option>
</PossibleStudies>

<!-- The port on which our web server listens: -->
<Port>
8000
</Port>

<!-- With the <ConfigData> elements one can define an arbitrary number
     of additional data for customization. There must be an attribute 'key'.

     The content is stored (as string) as value in a dictionary under the 
     key given by the 'key' attribute.

     These data can be used for example in the web pages via tags
     <ConfigData key=".." /> and so on, similar to <CourseName /> above. 
     
     In LaTeX templates below the data can be included with, e.g., 
     (%ConfigData.bla%).

Example:
-->
<ConfigData key="bla">blub</ConfigData>

<!-- A chunk of LaTeX header code that is put in the preamble of all
     LaTeX documents that are generated by this program. Put here all extra
     definitions like calls to "\usepackage" or common LaTeX macros 
     that you need in your exercises. See "LaTeXTemplate" below to learn 
     which facilities are included by default. This entry is optional. -->
<ExtraLaTeXHeader>
</ExtraLaTeXHeader>


<!-- The following regular expression is used to validate id's. As we use
Matrikel numbers usually we insist on numbers. For those not familiar with
regular expressions the following means that an id must start with a
digit between 1 and 9 which is followed by 4 or 5 digits from 0 to 9:
-->
<IdCheckRegExp>^[1-9][0-9]{4,5}$</IdCheckRegExp>
<!-- Another possibility could be to allow any string consisting of
letters a-z, A-Z, digits 0-9, dashes - and underscores: 

<IdCheckRegExp>^[a-zA-Z0-9_]*$</IdCheckRegExp>
-->


<!-- The following regular expression is used to check, whether an id is
     a guest id. Guest IDs have the following properties: They are excluded
     during export functions. One can authenticate with any password. -->
<GuestIdRegExp>^9999[0-9][0-9]$</GuestIdRegExp>
<!--<GuestIdRegExp>^_gast[a-zA-Z0-9_]*$</GuestIdRegExp>-->


<!-- The following switch tells OKUSON, whether exercise sheets are individual 
     (value 1) or not (value 0). This way OKUSON can be used easily for
     courses with "classical" exercise sheets (without multiple choice 
     exercises).  -->
<IndividualSheets>
1
</IndividualSheets>

<!-- The following switch decides, whether new registrations are possible 
     (value 1) or not (value 0). Note that the administrator can still
     register people over the web interface, if he gives the administrator
     password as the first of the two passwords, even when registration
     is switched off for regular participants. -->
<RegistrationPossible>
1
</RegistrationPossible>


<!-- The following switch decides, whether registrations for exams are 
     possible (value 1) or not (value 0). Note that you have to configure
     this registration in the templates in the html directory (see 
     html/examregistration.tpl for details. You might also want to add 
     a menu entry in the main menu to link to /html/examregistration.html. -->
<ExamRegistrationPossible>
1
</ExamRegistrationPossible>


<!-- The following switch decides, whether it is possible to choose the
     number of the tutoring group during registration. If this switch is
     off (value 0), each newly registered participant is put into group
     number 0. If this switch is on (value 1), each newly registered 
     participant can choose the group from the selection configured in
     the file specified below under <GroupInfoFile>, provided the chosen
     group is not yet full. -->
<GroupChoicePossible>
0
</GroupChoicePossible>


<!-- The following switch decides, whether participants can change groups
     after registration. -->
<GroupChangePossible>
0
</GroupChangePossible>


<!-- If this is set to 1 then registration is done in two steps.
     First, data are stored temporarily and an email with a validation
     code is sent to the new user. 
     This code must be input on the result page of the registration to
     finish the registration.
-->
<ValidateRegistration>
0
</ValidateRegistration>

<!-- Configure the text of the email sent to the participant to validate
     a registration. Adjust name of class and URL to the OKUSON server.
     VALKEY will be substituted by a random key generated by the server.
-->
<ValidateRegistrationMail>
Validierung der OKUSON-Anmeldung zur ???Vorlesung.

Bitte klicken Sie den folgenden Link (oder kopieren Sie ihn in Ihren Browser):
   https://www..../ValidateRegistration?valkey=VALKEY
um die Registrierung abzuschließen.
</ValidateRegistrationMail>

<!-- Specify here a regular expression for the accepted 
     email addresses for validated registration. 
     Default is all addresses. Other examples:
      ".*@rwth-aachen\.de$" 
      "(.*@rwth-aachen\.de$)|(.*\.rwth-aachen\.de$)"
-->
<ValidEmailAddresses>
.*@.*
</ValidEmailAddresses>

<!-- The following is a Python function that can automatically decide
     about the grading of a certain participant. This function is
     considered in two cases: (1) During the display of results for a
     participant and (2) During export of results. See also the next
     option about how to activate/deactivate this feature. -->
<GradingFunction>
def Grade(p,sl,mcscore,homescore,exams):
    '''This function decides about the grade of person p. sl is
       a list of sheets as returned by the function SheetList in the
       Exercises module. mcscore is the total sum of points in all
       closed sheets with counts value equal to 1. homescore is the total
       sum of points in the homework and exams is a list of length at 
       least 24 with one score corresponding to each of 24 exams (indexed
       from 0 to 23). If the participant did not take part in an exam,
       there is a zero in the corresponding position.'''
    if (mcscore+homescore >= 240 and 
        (exams[0]+exams[1] >= 50 or
         exams[2] >= 50 or
         exams[0]+exams[2] >= 50 or
         exams[1]+exams[2] >= 50)):
        return ('Sie bekommen den Schein.',1)
    else:
        return ('Sie bekommen leider keinen Schein.',0)
</GradingFunction>
